add nquarder to README.md
earthlab-education/Earth-Analytics-AY24 pull request #116
Opened 2024-09-03 17:30 UTC by nquarder

2024-09-03 18:54 UTC, eculler requested changes
The link doesn't work! Please fix.

2024-09-03 18:58 UTC, nquarder commented
@eculler thanks for catching this mistake! I think I've fixed it now. -NQ

2024-09-04 20:34 UTC, eculler submitted a review, later dismissed
w00t!

2024-09-06 00:37 UTC, cmq879 approved these changes

2024-09-11 16:06 UTC, nquarder commented
adding map of CR IA to posts/01-first-map directory cc: @atticusbaker & @npwelsh can you please review when you get a second? thanks! -NQ

2024-09-11 18:37 UTC, merged

2024-09-11 19:48 UTC, npwelsh commented on posts/01-first-map/nquarder/cedar-rapids.md
> +I went to Kirkwood CC in CR, IA 1999-2001. On July 1, 1966, Kirkwood was officially established, originally called "Area X Community College." The college immediately assumed responsibility for the f
Maybe change spell out CC and CR into Community College and Cedar Rapids respectively?  Other than that look great!

2024-09-11 19:49 UTC, npwelsh reviewed
Hi Nate, looks good! I like how you put two different polygons on the map looks great.  In cedar-rapids.md, have a small suggestion on line 3.  Other than that looks great!